name: polynesia
description: winner winner chicken dinner!
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  get: ^4.6.5
  equatable: ^2.0.5
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  connectivity: ^3.0.6
  crypto: ^3.0.2
  # toast
  fluttertoast: ^8.0.9
  # 远程图片加载
  cached_network_image: ^3.2.1
  date_format: ^2.0.6
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^0.5.3
  easy_refresh: ^3.0.4+2
  webview_flutter: ^3.0.4
  get_it: ^7.2.0
  bottom_sheet: ^3.1.1
  badges: ^2.0.3
  package_info_plus: ^1.4.3+1
  device_info_plus: ^4.1.2
  intl: ^0.17.0
  city_pickers: ^1.1.3
  flutter_pickers: ^2.1.8
  popup_window: ^1.0.0+3
  kumi_popup_window: ^2.0.0-nullsafety
  card_swiper: ^2.0.4
  marquee: ^2.2.3
  extended_nested_scroll_view: ^5.1.3
  loading_more_list: any
  pull_to_refresh_notification: any
  extended_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/guide/
